projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: server/src/generated/prisma.graphql
    extensions:
      prisma: server/database/prisma.yml